!------------------------------------------------------------------
! Code generated by GeneXproTools 4.0 on 03/03/2009 8:02:50 PM
! Training Samples:  246
! Fitness  Function: RRSE
! Training Fitness:  866.465722781635
! Training R-square: 0.976331602056821
!------------------------------------------------------------------

	real function gepModel(d)

		real, intent(in) :: d(0:1)

		real, parameter :: G1C0 = -7.840851
		real, parameter :: G1C1 = -9.934205
		real, parameter :: G2C0 = 3.905793
		real, parameter :: G2C1 = 4.713165
		real, parameter :: G3C0 = -2.181244
		real, parameter :: G3C1 = -6.156738

		real :: varTemp
		varTemp = 0.0

		varTemp = ((G1C0+sin(sqrt(d(0))))*((d(0)-G1C1)**(1.0/3.0)))
		varTemp = varTemp + (d(1)-(cos((d(1)**(1.0/3.0)))*(G2C0**3)))
		varTemp = varTemp + (d(0)-sqrt((sin((G3C1*d(1)))-G3C0)))

		gepModel = varTemp

	end function gepModel

