!------------------------------------------------------------------
! Code generated by GeneXproTools 4.0 on 03/03/2009 7:51:12 PM
! Training Samples:  246
! Fitness  Function: RRSE
! Training Fitness:  837.72824985952
! Training R-square: 0.963223027172055
!------------------------------------------------------------------

	real function gepModel(d)

		real, intent(in) :: d(0:1)

		real, parameter :: G1C0 = 8.82544
		real, parameter :: G1C1 = -3.335327
		real, parameter :: G2C0 = 0.85495
		real, parameter :: G2C1 = 9.354156
		real, parameter :: G3C0 = 5.393677
		real, parameter :: G3C1 = 9.864624

		real :: varTemp
		varTemp = 0.0

		varTemp = (d(0)-(G1C0**2))
		varTemp = varTemp + (((G2C0*d(0))-d(0))+atan((d(1)-G2C1)))
		varTemp = varTemp + (d(1)-(log((G3C0**2))-atan((d(1)/G3C0))))

		gepModel = varTemp

	end function gepModel

